### PR TITLE
Introduce validateTokenResult callback

### PR DESCRIPTION
**Pull request by bakulf**

### CODE REVIEW

**Comment by vladikoff** [comment]
Besides this override, we also need to patch the `keys_jwk` param and allow the use of the lib without scoped keys BUT with PKCE https://github.com/mozilla/fxa-crypto-relier/issues/36

**Comment by bakulf** [comment]
Is it something we want to do it for the token validation? Probably not. am I right?

**Comment by vladikoff** [comment]
@bakulf probably not ! cc @shane-tomlinson

**Comment by shane-tomlinson** [comment]
I have opened https://github.com/mozilla/fxa-crypto-relier/pull/39 as a more general solution for this. Closing.

**Pull request closed without merging**
